---
# tasks file for roles/createnetwork
- name: create a network
  gcp_compute_network:
    name: "{{ network.network_name | default('network-instance') }}"    
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: network

- name: create a firewall
  gcp_compute_firewall:
    name: "{{ network.firewall_name | default('firewall-instance') }}"
    allowed:
    - ip_protocol: tcp
      ports:
      - "0-65535"
    - ip_protocol: icmp
    source_ranges: 
      - "0.0.0.0/0"
    network: "{{ network }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
