---
# tasks file for roles/installlab

- name: update cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: install prereqisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git
      - python3-pip
    state: latest

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker.list
    update_cache: yes

- name: install docker-ce
  apt:
    name: docker-ce
    update_cache: yes
    state: latest

- name: enable docker 
  service:
    name: docker
    state: restarted
    enabled: yes

- name: get docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 755

- name: install Docker sdk for python
  pip:
    name:
      - docker
      - docker-compose

- name: Get confluent repo
  git:
    repo: https://github.com/confluentinc/training-developer-src.git 
    dest: confluent-dev
    depth: 1
    version: 5.4.0-v1.1.0
  become: no

- name: run update-hosts.sh
  command: "bash confluent-dev/update-hosts.sh"

- name: Make docker-compose up zookeper kafka control-center and tools ready
  docker_compose:
    project_src: confluent-dev
    state: present
    services:
      - zookeeper
      - kafka
      - control-center
      - tools
