---
# tasks file for roles/deletevms
- name: delete vms
  gcp_compute_instance:
    name: "{{ item.vm_name }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: absent
  with_items: "{{ instance_config }}"

- name: delete addresses
  gcp_compute_address:
    name: "{{ item.vm_address_name }}"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
  with_items: "{{ instance_config }}"
