---
# tasks file for roles/createnetwork

- name: delete firewall
  gcp_compute_firewall:
    name: "{{ network.network_name | default('firewall-instance') }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent


- name: delete network
  gcp_compute_network:
    name: "{{ network.firewall_name | default('network-instance') }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent


